server:
  port: 2003

spring:
  application:
    name: seata-account-service
  #    nacos:
  #      discovery:
  #        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata_account?rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456


seata:
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: localhost:8848
      group: "SEATA_GROUP"
      namespace: ""
      username: "nacos"
      password: "nacos"
  tx-service-group: my_test_tx_group


feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml


